---
- hosts: aeadwmappb2b39
  become: true
  gather_facts: false
  tasks:
      - name: Changing the password for user
        user:
            name: sudip
            password: "{{ 'Sudipwinc@123' | password_hash('sha512') }}"
            update_password: always
...
